/** Full savage roast pool — shared between game-listener and the nag timer in spin. */
export const ROASTS: ReadonlyArray<string> = [
    "How do you even function daily?",
    "Explain it like you're five?",
    "Clearly, you lack comprehension.",
    "Your ignorance is exhausting.",
    "Did that strain your brain?",
    "Go back to school.",
    "You must be slow.",
    "Is English your second language?",
    "You can't be serious.",
    "That is purely pathetic.",
    "Are you always this dense?",
    "A toddler understands this better.",
    "Your opinion is completely worthless.",
    "Did you leave your brain behind?",
    "This is embarrassingly simple.",
    "You are a total waste of time.",
    "Stop talking, you are embarrassing yourself.",
    "No one cares about your thoughts.",
    "You bring down the average IQ.",
    "Are you incapable of basic thought?",
    "The closest you'll come to a brainstorm is a light drizzle.",
    "You look smarter in pictures.",
    "Honestly, I'm just impressed you could read this.",
    "We need an evacuation plan for your bathroom breaks.",
    "Your family tree didn't have enough branches.",
    "Your existence proves that intelligent design doesn't exist.",
    "Your face just made me agnostic.",
    "Were you dropped a lot as a baby?",
    "Your brain is mush.",
    "You smell terrible today. And every other day.",
    "You should come with a warning label.",
    "I'm still deciding whether you're the weakest link or the missing link.",
    "I have neither the time nor the crayons necessary to explain this to you.",
    "You are an oxygen bandit.",
    "I've had bowel movements more attractive than you.",
    "You should be in charge of unclogging every clogged toilet.",
    "Dang, you're still alive?",
    "There's stupid leaking out of your mouth again.",
    "You do you. Because God knows no one else will.",
    "I think I got brain damage just from listening to you talk.",
    "I always appreciate your advice, so I know what not to do.",
    "You look like a before picture.",
    "If you doubled your IQ, it'd be zero.",
    "Next time you're in town, be sure not to message me.",
    "Are you drunk right now?",
    "You could have been an extra in Chernobyl.",
    "You're a marvel of stupidity.",
    "What doesn't kill you disappoints the rest of us.",
    "I was in such a good mood until you spoke.",
    "Did you develop your personality in a car crash?",
    "I can't talk to you right now. My doctor said I should avoid things that make me nauseous.",
    "You snatched defeat from the jaws of victory.",
    "I heard you've fallen on hard times. I just hope they continue.",
    "I smell smoke. Were you thinking too hard again?",
    "Being bitter won't make you prettier.",
    "We live in very divisive times, but we can all agree that you're a moron.",
    "They say looks can be deceiving, but you're actually as stupid as you look.",
    "If it ever seems like nothing is going your way, just know that it's because you're a bad person.",
    "I envy everyone who hasn't met you.",
    "I'm blessed to have so many good friends. Then there's you.",
    "Your birthday should be a global day of mourning.",
    "When you were born, the world really needed an undo button.",
    "If ignorance is bliss, you must be ecstatic at all times.",
    "You'd fail a personality test.",
    "Did you sniff a lot of glue as a kid?",
    "You're proof that accidents happen.",
    "We all just received some horrible news. You still exist.",
    "I'd never make you explain yourself. I don't want you to pass out.",
    "They need to give you a Guinness World Record for being the most useless person ever.",
    "There really is one born every minute.",
    "Can I switch to the timeline where you don't exist?",
    "You're completely right, except for everything you just said.",
    "You'll go far someday. And I hope you stay there.",
    "Did you forget to breathe again?",
    "You're proof that the gene pool needs lifeguards.",
    "How are you still here? Isn't it trash day?",
    "Your gene pool needs more chlorine.",
    "I will not have a battle of wits with an unarmed opponent.",
    "It's impossible to underestimate you.",
    "Evolution hit a roadblock when you were born.",
    "Did you just wake up from a coma?",
    "Though some people fear success, rest assured, you have nothing to worry about.",
    "Your existence is a conspiracy against the human race.",
    "The key to happiness is to avoid you at all costs.",
    "You give idiots a bad name.",
    "I'm not very religious, but I believe God is testing me whenever you walk into the room.",
    "You're about as useful as a screen door on a submarine.",
    "The only time you're not as dumb as you look is when I close my eyes.",
    "You're not a friend. You're a chore.",
    "You look like someone fed you after midnight.",
    "You're really holding back humanity.",
    "You should write a self-help book. Call it How to Live as an Idiot.",
    "If we really are living in a simulation, you're the bug in the program.",
    "You're weapons-grade stupid.",
    "Even Bob Ross would call you a mistake.",
    "If I gave you a penny for your thoughts, I'd get change back.",
    "Our parents told us we could be anything, and you chose disappointment.",
    "There's this great book I'll recommend you, if you ever learn how to read.",
    "You should teach people how to clear their minds. Since you're always empty-headed.",
    "I think of you often. On trash day.",
    "Your birth control of choice appears to be your personality.",
    "It was great seeing you yesterday. Also, you're stupid.",
    "If you're going to be two-faced, at least make one of them cute.",
    "If your IQ were just a little higher you could be an idiot.",
    "You're not the dumbest person alive, but you better hope they're taking vitamins.",
    "I saw you the other day. I was relieved that you didn't see me.",
    "I expect nothing and am still disappointed.",
    "The bar is beneath the ground and we need a metal detector to find it.",
    "I'm trying to get rid of some junk today. I just need to lure you into a trash bin.",
    "I'd love to help you out. Which way did you get in?",
    "Light travels faster than sound, which is why you seemed bright until you spoke.",
    "I'm tired of seeing your stupid face.",
    "You're not the brightest crayon in the box.",
    "You're as bright as beige.",
    "You look like something I drew with my left hand.",
    "Our group's average IQ just plummeted now that you're here.",
    "All my friends are coming to my birthday party. That's why you won't be there.",
    "If genius skips a generation, your parents must be masterminds.",
    "Don't bother covering up your answers. No one's gonna cheat off you.",
    "You're incredible. Incredibly stupid.",
    "Silence is golden, but for you, it's actually diamond status.",
    "Your mom wishes the stork left a gift receipt with you.",
    "Your parents didn't put many points in intelligence when they created you.",
    "If zombies tried eating your brains, they'd starve.",
    "If you were any dumber I'd have to water you once a day.",
    "You bring as much joy to the world as a wet sock.",
    "You're a gray sprinkle on a Funfetti cupcake.",
    "Your face would make an onion cry.",
    "Don't be ashamed of who you are. That's your parents' job.",
    "You remind me of my dog, who chases his own tail for entertainment.",
    "Were you drinking from the toilet again?",
    "You're why shampoo bottles have instructions.",
    "If you ever had to speak your mind, you'd be silent.",
    "That sounds like a you problem.",
    "You are like a cloud. When you disappear, it's a beautiful day.",
    "We're hoping you'll join the team this year. We need a mascot.",
    "I'd say you're dumb as a rock, but at least rocks are useful.",
    "I'm not insulting you. I'm describing you.",
    "If I throw a stick, will you leave?",
    "Don't worry, you weren't adopted. No one would do that on purpose.",
    "If stupidity were a crime, you'd be serving a life sentence.",
    "You bring joy to every room you exit.",
    "You have a face for radio.",
    "You're as useful as a chocolate teapot.",
    "You're about as bright as a cave.",
    "You should become an astronaut. We need you as far away from Earth as possible.",
    "Your mom gave me $20 to hang out with you.",
];

export const randomRoast = (): string =>
    ROASTS[Math.floor(Math.random() * ROASTS.length)];
